<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.0" os="" host="DESKTOP-H4RRNSP"><DocLocation><![CDATA[D:\ALM Octane Test\TC4_Search Flight]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[TC4_Search Flight]]></DName>
<Res><![CDATA[TC4_Search Flight]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:10]]></Time>
<TimeTick>1540374730</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:10]]></Time>
<TimeTick>1540374730</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:10]]></Time>
<TimeTick>1540374730</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[userName.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:11]]></Time>
<TimeTick>1540374731</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("password")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Sign-In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:11]]></Time>
<TimeTick>1540374731</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Sign-In.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Image("Sign-In")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:24]]></Time>
<TimeTick>1540374804</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[fromPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"fromPort"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:24]]></Time>
<TimeTick>1540374804</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[fromPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[4]/TD[2]/SELECT[1]<br>|Visible Items = 0<br>Visible = -1<br>Name = fromPort<br>Items Count = 10<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:24]]></Time>
<TimeTick>1540374804</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="63" status="Warning" nType="Description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[fromPort]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromPort")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="62" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[fromPort]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromPort")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="61" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:24]]></Time>
<TimeTick>1540374804</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;fromPort&quot; (of class WebList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (7): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;fromPort&quot;).Select &quot;London&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:24]]></Time>
<TimeTick>1540374804</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="65" status="Failed" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:45]]></Time>
<TimeTick>1540374825</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[fromMonth]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"fromMonth"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:45]]></Time>
<TimeTick>1540374825</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[fromMonth]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[5]/TD[2]/SELECT[1]<br>|Visible Items = 0<br>Visible = -1<br>Name = fromMonth<br>Items Count = 12<br>Html Id = <br>default value = October<br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:45]]></Time>
<TimeTick>1540374825</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="111" status="Warning" nType="Description" Source="Action1" SourceLine="6" >
<Disp><![CDATA[fromMonth]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromMonth")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="110" status="Failed" nType="Run Error" Source="Action1" SourceLine="6" >
<Disp><![CDATA[fromMonth]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromMonth")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="109" status="Failed" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="64" status="Failed" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:45]]></Time>
<TimeTick>1540374825</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;fromMonth&quot; (of class WebList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (8): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;fromMonth&quot;).Select &quot;August&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:53:45]]></Time>
<TimeTick>1540374825</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="113" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:06]]></Time>
<TimeTick>1540374846</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[fromDay]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"fromDay"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:06]]></Time>
<TimeTick>1540374846</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[fromDay]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[5]/TD[2]/SELECT[2]<br>|Visible Items = 0<br>Visible = -1<br>Name = fromDay<br>Items Count = 31<br>Html Id = <br>default value = 24<br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:06]]></Time>
<TimeTick>1540374846</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="159" status="Warning" nType="Description" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromDay]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromDay")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="158" status="Failed" nType="Run Error" Source="Action1" SourceLine="7" >
<Disp><![CDATA[fromDay]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromDay")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="157" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="112" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:06]]></Time>
<TimeTick>1540374846</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;fromDay&quot; (of class WebList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (9): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;fromDay&quot;).Select &quot;27&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:06]]></Time>
<TimeTick>1540374846</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="161" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:27]]></Time>
<TimeTick>1540374867</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[toPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"toPort"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:27]]></Time>
<TimeTick>1540374867</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[toPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[6]/TD[2]/SELECT[1]<br>|Visible Items = 0<br>Visible = -1<br>Name = toPort<br>Items Count = 10<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:27]]></Time>
<TimeTick>1540374867</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="206" status="Warning" nType="Description" Source="Action1" SourceLine="8" >
<Disp><![CDATA[toPort]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toPort")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="205" status="Failed" nType="Run Error" Source="Action1" SourceLine="8" >
<Disp><![CDATA[toPort]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toPort")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="204" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="160" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:27]]></Time>
<TimeTick>1540374867</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;toPort&quot; (of class WebList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (10): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;toPort&quot;).Select &quot;Portland&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:27]]></Time>
<TimeTick>1540374867</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="208" status="Failed" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:48]]></Time>
<TimeTick>1540374888</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[servClass]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"servClass"&nbsp;(of&nbsp;class&nbsp;WebRadioGroup).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:48]]></Time>
<TimeTick>1540374888</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[servClass]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebRadioGroup<br>Html Tag = INPUT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[9]/TD[2]/FONT[1]/FONT[1]/INPUT[1]<br>|Visible = -1<br>Name = servClass<br>Items Count = 3<br>Html Id = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:48]]></Time>
<TimeTick>1540374888</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="253" status="Warning" nType="Description" Source="Action1" SourceLine="9" >
<Disp><![CDATA[servClass]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("servClass")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="252" status="Failed" nType="Run Error" Source="Action1" SourceLine="9" >
<Disp><![CDATA[servClass]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("servClass")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="251" status="Failed" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="207" status="Failed" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:48]]></Time>
<TimeTick>1540374888</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;servClass&quot; (of class WebRadioGroup).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (11): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebRadioGroup(&quot;servClass&quot;).Select &quot;Business&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:54:48]]></Time>
<TimeTick>1540374888</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="255" status="Failed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:55:09]]></Time>
<TimeTick>1540374909</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[airline]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"airline"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:55:09]]></Time>
<TimeTick>1540374909</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[airline]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[10]/TD[2]/SELECT[1]<br>|Visible Items = 0<br>Visible = -1<br>Name = airline<br>Items Count = 4<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:55:09]]></Time>
<TimeTick>1540374909</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="300" status="Warning" nType="Description" Source="Action1" SourceLine="10" >
<Disp><![CDATA[airline]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("airline")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="299" status="Failed" nType="Run Error" Source="Action1" SourceLine="10" >
<Disp><![CDATA[airline]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("airline")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="298" status="Failed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="254" status="Failed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:55:09]]></Time>
<TimeTick>1540374909</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;airline&quot; (of class WebList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (12): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;airline&quot;).Select &quot;Blue Skies Airlines&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:55:09]]></Time>
<TimeTick>1540374909</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="302" status="Failed" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:55:30]]></Time>
<TimeTick>1540374930</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[findFlights]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"findFlights"&nbsp;(of&nbsp;class&nbsp;Image).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:55:30]]></Time>