<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.0" os="" host="DESKTOP-H4RRNSP"><DocLocation><![CDATA[D:\ALM Octane Test\TC6_EditProfile]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[TC6_EditProfile]]></DName>
<Res><![CDATA[TC6_EditProfile]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/25/2018 - 10:43:03]]></Time>
<TimeTick>1540438983</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/25/2018 - 10:43:03]]></Time>
<TimeTick>1540438983</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/25/2018 - 10:43:03]]></Time>
<TimeTick>1540438983</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[userName.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5bd137d620821b10"]]></Details>
<Time><![CDATA[10/25/2018 - 10:43:04]]></Time>
<TimeTick>1540438984</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("password")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Sign-In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/25/2018 - 10:43:04]]></Time>
<TimeTick>1540438984</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Sign-In.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Image("Sign-In")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/25/2018 - 10:43:54]]></Time>
<TimeTick>1540439034</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[PROFILE.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/25/2018 - 10:43:54]]></Time>
<TimeTick>1540439034</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[PROFILE.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").Link("PROFILE")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:11]]></Time>
<TimeTick>1540439051</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["A"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:11]]></Time>
<TimeTick>1540439051</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[firstName.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("firstName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["A"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:11]]></Time>
<TimeTick>1540439051</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[lastName.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("lastName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1234"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:11]]></Time>
<TimeTick>1540439051</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[phone.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("phone")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a@gmail.com"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:11]]></Time>
<TimeTick>1540439051</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[email.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("email")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:11]]></Time>
<TimeTick>1540439051</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[address1.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("address1")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:12]]></Time>
<TimeTick>1540439052</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[address2.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("address2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:12]]></Time>
<TimeTick>1540439052</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[city.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("city")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:12]]></Time>
<TimeTick>1540439052</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="47" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[state.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("state")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1223"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:12]]></Time>
<TimeTick>1540439052</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[postalCode.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("postalCode")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["VIETNAM"]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:12]]></Time>
<TimeTick>1540439052</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="53" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[country.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebList("country")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[profile_submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:13]]></Time>
<TimeTick>1540439053</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[profile_submit.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").Image("profile submit")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/25/2018 - 10:44:13]]></Time>
<TimeTick>1540439053</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="57" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10/25/2018 - 10:43:03" eTime="10/25/2018 - 10:44:13" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[TC6_EditProfile Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10/25/2018 - 10:43:00" eTime="10/25/2018 - 10:44:13" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test TC6_EditProfile Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>