<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.0" os="" host="DESKTOP-H4RRNSP"><DocLocation><![CDATA[D:\ALM Octane Test\TC3_Sign In]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[TC3_Sign In]]></DName>
<Res><![CDATA[TC3_Sign In]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:50:50]]></Time>
<TimeTick>1540374650</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:50:50]]></Time>
<TimeTick>1540374650</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[userName]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"userName"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:50:50]]></Time>
<TimeTick>1540374650</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[userName]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[2]/TD[3]/FORM[1]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[2]/TD[2]/INPUT[1]<br>|rows = 0<br>placeholder = <br>Name = userName<br>Max Length = 524288<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:50:50]]></Time>
<TimeTick>1540374650</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" status="Warning" nType="Description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[userName]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="52" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[userName]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="51" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="50" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:50:50]]></Time>
<TimeTick>1540374650</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;userName&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (2): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).WebEdit(&quot;userName&quot;).Set &quot;a&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:50:50]]></Time>
<TimeTick>1540374650</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:11]]></Time>
<TimeTick>1540374671</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"password"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:11]]></Time>
<TimeTick>1540374671</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = password<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[2]/TD[3]/FORM[1]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[3]/TD[2]/INPUT[1]<br>|rows = 0<br>placeholder = <br>Name = password<br>Max Length = 524288<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:11]]></Time>
<TimeTick>1540374671</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="100" status="Warning" nType="Description" Source="Action1" SourceLine="1" >
<Disp><![CDATA[password]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("password")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="99" status="Failed" nType="Run Error" Source="Action1" SourceLine="1" >
<Disp><![CDATA[password]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("password")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="98" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="54" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:11]]></Time>
<TimeTick>1540374671</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;password&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (3): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).WebEdit(&quot;password&quot;).Set &quot;a&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:11]]></Time>
<TimeTick>1540374671</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="102" status="Failed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:32]]></Time>
<TimeTick>1540374692</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Sign-In]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Sign-In"&nbsp;(of&nbsp;class&nbsp;Image).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:32]]></Time>
<TimeTick>1540374692</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Sign-In]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Image<br>Html Tag = INPUT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[2]/TD[3]/FORM[1]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[4]/TD[2]/DIV[1]/INPUT[1]<br>|Width = 58<br>Visible = -1<br>Name = login<br>Image Type = Image Button<br>Html Id = <br>Height = 17<br>file name = btn_signin.gif<br>DHTML Class = <br>Alt = Sign-In<br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:32]]></Time>
<TimeTick>1540374692</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="147" status="Warning" nType="Description" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Sign-In]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Image("Sign-In")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="146" status="Failed" nType="Run Error" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Sign-In]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Image("Sign-In")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="145" status="Failed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="101" status="Failed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:32]]></Time>
<TimeTick>1540374692</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Sign-In&quot; (of class Image).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (4): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).Image(&quot;Sign-In&quot;).Click 38,10&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:51:32]]></Time>
<TimeTick>1540374692</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="149" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:03]]></Time>
<TimeTick>1540374723</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[SIGN-OFF]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"SIGN-OFF"&nbsp;(of&nbsp;class&nbsp;WebElement).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:03]]></Time>
<TimeTick>1540374723</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[SIGN-OFF]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebElement<br>Html Tag = TD<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[2]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]<br>|Visible = -1<br>innertext = ITINERARY<br>Html Id = <br>DHTML Class = mouseOut<br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:03]]></Time>
<TimeTick>1540374723</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="192" status="Warning" nType="Description" Source="Action1" SourceLine="3" >
<Disp><![CDATA[SIGN-OFF]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebElement("SIGN-OFF")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="191" status="Failed" nType="Run Error" Source="Action1" SourceLine="3" >
<Disp><![CDATA[SIGN-OFF]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebElement("SIGN-OFF")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="190" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="148" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:03]]></Time>
<TimeTick>1540374723</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:03]]></Time>
<TimeTick>1540374723</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;SIGN-OFF&quot; (of class WebElement).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (8): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebElement(&quot;SIGN-OFF&quot;).Check CheckPoint(&quot;SIGN-OFF&quot;)&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:03]]></Time>
<TimeTick>1540374723</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="195" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebElement("SIGN-OFF")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="194" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:06]]></Time>
<TimeTick>1540374726</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:06]]></Time>
<TimeTick>1540374726</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="199" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours.Sync]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="198" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/24/2018 - 16:52:06]]></Time>
<TimeTick>1540374726</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="200" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="193" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10/24/2018 - 16:50:29" eTime="10/24/2018 - 16:52:06" passed="0" failed="8" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[TC3_Sign In Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10/24/2018 - 16:50:26" eTime="10/24/2018 - 16:52:06" passed="0" failed="8" warnings="4" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test TC3_Sign In Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>