<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.0" os="" host="DESKTOP-H4RRNSP"><DocLocation><![CDATA[D:\ALM Octane Test\TC1_Test Register]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[TC1_Test Register]]></DName>
<Res><![CDATA[TC1_Test Register]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:25]]></Time>
<TimeTick>1540367065</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:25]]></Time>
<TimeTick>1540367065</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[REGISTER]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"REGISTER"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:25]]></Time>
<TimeTick>1540367065</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[REGISTER]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[2]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/A[1]<br>|Visible = -1<br>Text = REGISTER<br>Name = REGISTER<br>Html Id = <br>Href = http://newtours.demoaut.com/mercuryregister.php?osCsid=30509cdc5a0962e7e40db2ddb8b8fb7e<br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:25]]></Time>
<TimeTick>1540367065</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" status="Warning" nType="Description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[REGISTER]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Link("REGISTER")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="53" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[REGISTER]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Link("REGISTER")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="52" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="51" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:25]]></Time>
<TimeTick>1540367065</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;REGISTER&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (2): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).Link(&quot;REGISTER&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:25]]></Time>
<TimeTick>1540367065</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[firstName]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"firstName"&nbsp;object's&nbsp;parent&nbsp;"Register:&nbsp;Mercury&nbsp;Tours"&nbsp;(class&nbsp;Page).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[firstName]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[4]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/TABLE[1]/TBODY[1]/TR[5]/TD[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[2]/TD[2]/INPUT[1]<br>|rows = 0<br>placeholder = <br>Name = firstName<br>Max Length = 60<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="88" status="Warning" nType="Description" Source="Action1" SourceLine="1" >
<Disp><![CDATA[firstName]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("firstName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="87" status="Failed" nType="Run Error" Source="Action1" SourceLine="1" >
<Disp><![CDATA[firstName]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("firstName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="86" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="55" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;firstName&quot; object's parent &quot;Register: Mercury Tours&quot; (class Page).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Line (3): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Register: Mercury Tours&quot;).WebEdit(&quot;firstName&quot;).Set &quot;hong&quot;&quot;. ]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" status="Failed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["nguyen"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="94" Source="Action1" SourceLine="2" >
<Disp><![CDATA[lastName.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("lastName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0987654321"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:47]]></Time>
<TimeTick>1540367087</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="97" Source="Action1" SourceLine="2" >
<Disp><![CDATA[phone.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("phone")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hong@gmail.com"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:48]]></Time>
<TimeTick>1540367088</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="100" Source="Action1" SourceLine="2" >
<Disp><![CDATA[userName.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hn"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:48]]></Time>
<TimeTick>1540367088</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="103" Source="Action1" SourceLine="2" >
<Disp><![CDATA[address1.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("address1")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["vietnam"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:48]]></Time>
<TimeTick>1540367088</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" Source="Action1" SourceLine="2" >
<Disp><![CDATA[address2.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("address2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ha noi"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:48]]></Time>
<TimeTick>1540367088</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="109" Source="Action1" SourceLine="2" >
<Disp><![CDATA[city.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("city")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["dong da"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:49]]></Time>
<TimeTick>1540367089</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="112" Source="Action1" SourceLine="2" >
<Disp><![CDATA[state.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("state")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["34"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:49]]></Time>
<TimeTick>1540367089</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="115" Source="Action1" SourceLine="2" >
<Disp><![CDATA[postalCode.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("postalCode")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["VIETNAM"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:49]]></Time>
<TimeTick>1540367089</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="118" Source="Action1" SourceLine="2" >
<Disp><![CDATA[country.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebList("country")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hong"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:49]]></Time>
<TimeTick>1540367089</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="121" Source="Action1" SourceLine="2" >
<Disp><![CDATA[email.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("email")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5bd02006259d58b8750b459c78be"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:50]]></Time>
<TimeTick>1540367090</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="124" Source="Action1" SourceLine="2" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("password")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[confirmPassword.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5bd0200bee88beeb1c8f8102bdba"]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:50]]></Time>
<TimeTick>1540367090</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="127" Source="Action1" SourceLine="2" >
<Disp><![CDATA[confirmPassword.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").WebEdit("confirmPassword")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[register.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/24/2018 - 14:44:50]]></Time>
<TimeTick>1540367090</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="130" Source="Action1" SourceLine="2" >
<Disp><![CDATA[register.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours").Image("register")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="93" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/24/2018 - 14:45:13]]></Time>
<TimeTick>1540367113</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Thank you for registering.]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[10/24/2018 - 14:45:13]]></Time>
<TimeTick>1540367113</TimeTick>
<HtmlStep rID="T32">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Checkpoint "Thank you for registering. You may now  sign-in using the user name and password you've just entered.": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 10/24/2018 - 14:45:13</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">Thank you for registering. You may now  sign-in using the user name and password you've just entered. Results&nbsp;</td></tr>
<tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Property Value&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<TD class="Text" Title="">innertext&nbsp;</TD>
				<TD class="Text" Title=""> Thank you for registering. You may now  sign-in using the user name and password you've just entered. &nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1540367113</TimeTick>
<NodeArgs eType="Verification" icon="12" nRep="134" status="Passed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Checkpoint "Thank you for registering. You may now  sign-in using the user name and password you've just entered."]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 2").WebElement("Thank you for registering.")]]></ASHilite>
</BtmPane>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="12" nRep="133" status="Passed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Thank you for registering.]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 2").WebElement("Thank you for registering.")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours_2.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/24/2018 - 14:45:13]]></Time>
<TimeTick>1540367113</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="137" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours_2.Sync]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="132" status="Passed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/24/2018 - 14:45:13]]></Time>
<TimeTick>1540367113</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="138" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="89" status="Failed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10/24/2018 - 14:44:04" eTime="10/24/2018 - 14:45:14" passed="1" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[TC1_Test Register Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10/24/2018 - 14:44:01" eTime="10/24/2018 - 14:45:14" passed="1" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test TC1_Test Register Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>