<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.0" os="" host="DESKTOP-H4RRNSP"><DocLocation><![CDATA[D:\ALM Octane Test\TC8_BookFlight]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[TC8_BookFlight]]></DName>
<Res><![CDATA[TC8_BookFlight]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:27]]></Time>
<TimeTick>1540536747</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:27]]></Time>
<TimeTick>1540536747</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:27]]></Time>
<TimeTick>1540536747</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[userName.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5bd2b84e328386dd"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:28]]></Time>
<TimeTick>1540536748</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("password")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Sign-In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:28]]></Time>
<TimeTick>1540536748</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Sign-In.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Image("Sign-In")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:35]]></Time>
<TimeTick>1540536755</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[tripType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["oneway"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:35]]></Time>
<TimeTick>1540536755</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[tripType.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("tripType")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[passCount.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:35]]></Time>
<TimeTick>1540536755</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passCount.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("passCount")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[fromPort.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["New York"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:36]]></Time>
<TimeTick>1540536756</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[fromPort.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromPort")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[fromMonth.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["September"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:36]]></Time>
<TimeTick>1540536756</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[fromMonth.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromMonth")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[fromDay.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["27"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:36]]></Time>
<TimeTick>1540536756</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[fromDay.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromDay")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[toPort.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sydney"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:36]]></Time>
<TimeTick>1540536756</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[toPort.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toPort")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[toMonth.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["November"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:36]]></Time>
<TimeTick>1540536756</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[toMonth.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toMonth")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[toDay.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["28"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:36]]></Time>
<TimeTick>1540536756</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[toDay.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toDay")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[servClass.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:37]]></Time>
<TimeTick>1540536757</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[servClass.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("servClass")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[airline.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Blue Skies Airlines"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:37]]></Time>
<TimeTick>1540536757</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[airline.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("airline")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[findFlights.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:37]]></Time>
<TimeTick>1540536757</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[findFlights.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").Image("findFlights")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Select a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:38]]></Time>
<TimeTick>1540536758</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[outFlight.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Unified Airlines$363$281$11:24"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:38]]></Time>
<TimeTick>1540536758</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[outFlight.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").WebRadioGroup("outFlight")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[inFlight.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Pangea Airlines$632$282$16:37"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:38]]></Time>
<TimeTick>1540536758</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="59" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[inFlight.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").WebRadioGroup("inFlight")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[reserveFlights.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:38]]></Time>
<TimeTick>1540536758</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="62" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[reserveFlights.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").Image("reserveFlights")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="55" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Select a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Book a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:39]]></Time>
<TimeTick>1540536759</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[passFirst0.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mai"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:39]]></Time>
<TimeTick>1540536759</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passFirst0.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passFirst0")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[passLast0.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nguyen"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:39]]></Time>
<TimeTick>1540536759</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="69" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passLast0.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passLast0")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[pass.0.meal.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Hindu"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:40]]></Time>
<TimeTick>1540536760</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="72" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[pass.0.meal.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("pass.0.meal")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[passFirst1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["A"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:40]]></Time>
<TimeTick>1540536760</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="75" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passFirst1.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf25.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passFirst1")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[passLast1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AAA"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:40]]></Time>
<TimeTick>1540536760</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="78" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passLast1.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf26.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passLast1")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[passFirst2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AB"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:41]]></Time>
<TimeTick>1540536761</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="81" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passFirst2.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf27.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passFirst2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[passLast2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AB"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:41]]></Time>
<TimeTick>1540536761</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="84" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passLast2.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf28.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passLast2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[creditnumber.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123467687"]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:41]]></Time>
<TimeTick>1540536761</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="87" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[creditnumber.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf29.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("creditnumber")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[buyFlights.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:42]]></Time>
<TimeTick>1540536762</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[buyFlights.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf30.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").Image("buyFlights")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="65" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Book a Flight: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Flight Confirmation: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:42]]></Time>
<TimeTick>1540536762</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Your itinerary has been]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:42]]></Time>
<TimeTick>1540536762</TimeTick>
<HtmlStep rID="T38">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Checkpoint "Your itinerary has been booked!": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 10/26/2018 - 13:52:43</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">Your itinerary has been booked! Results&nbsp;</td></tr>
<tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Property Value&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<TD class="Text" Title="">innertext&nbsp;</TD>
				<TD class="Text" Title="">Your itinerary has been booked!&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1540536763</TimeTick>
<NodeArgs eType="Verification" icon="11" nRep="94" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Checkpoint "Your itinerary has been booked!"]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf33.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Flight Confirmation: Mercury").WebElement("Your itinerary has been")]]></ASHilite>
</BtmPane>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="11" nRep="93" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Your itinerary has been]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf32.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Flight Confirmation: Mercury").WebElement("Your itinerary has been")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[backtoflights.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:43]]></Time>
<TimeTick>1540536763</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="97" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[backtoflights.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf34.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Flight Confirmation: Mercury").Image("backtoflights")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="92" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Confirmation: Mercury]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf31.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Flight Confirmation: Mercury")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Select a Flight: Mercury_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:43]]></Time>
<TimeTick>1540536763</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Select a Flight: Mercury_2.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:43]]></Time>
<TimeTick>1540536763</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="101" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Select a Flight: Mercury_2.Sync]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf36.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="100" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Select a Flight: Mercury_2]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf35.xml]]></Path>
<ASHilite><![CDATA[Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/26/2018 - 13:52:43]]></Time>
<TimeTick>1540536763</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="102" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10/26/2018 - 13:52:27" eTime="10/26/2018 - 13:52:44" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[TC8_BookFlight Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10/26/2018 - 13:52:24" eTime="10/26/2018 - 13:52:44" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test TC8_BookFlight Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>